# Generated by Django 5.2.6 on 2025-12-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjobmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Pending', max_length=20, null=True),
        ),
    ]
